[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
orbit_len = "7ZigWsEmK5JAW2mgKP19yRhcwt3gTpFMfkttXG7Hj9MF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
