[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
orbit_len = "QoB7dVkkZr3oLb95DMpSptvUF8mTygDHNjFQh5y5RAb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=f84a6f24-1feb-4290-bc2f-4fc95cf5e7f0"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/raydium.ts"
